# Generated by Django 3.0.2 on 2020-01-24 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('about', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='img/photo')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('credit_card', models.CharField(default='', max_length=30)),
                ('security_number', models.IntegerField(default=0)),
                ('paying', models.CharField(choices=[('BANK', 'Credit card'), ('HOME', 'Cash on delivery')], default='HOME', max_length=4)),
                ('delivery', models.CharField(choices=[('HOME', 'To your home'), ('PICK', 'To pickup address')], default='HOME', max_length=4)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webshopApp.Cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webshopApp.User')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshopApp.Item'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshopApp.User'),
        ),
    ]
