# Generated by Django 3.0.2 on 2020-01-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshopApp', '0003_auto_20200127_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='cart',
        ),
        migrations.AddField(
            model_name='purchase',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
